# yaml-language-server: $disable
apiVersion: apps/v1
kind: Deployment
metadata:
  ## Then name of the local release, example: hrlm install "local-nginx"
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
